site_name: 'ugodoc'
site_url: 'https://ugoproto.github.io/ugodoc/'
repo_name: 'ugodoc' # see doc, for bitbucket, gitlab
repo_url: 'https://github.com/ugoproto/ugodoc.git'
# include a link to the repository of your project 
# repository is hosted in a private environment, the service logo can be set explicitly by setting
# extra.repo_icon to github, gitlab or bitbucket
site_description: 'A Data Science documentation website.'
site_author: 'Ugo Sparks'
copyright: '© Ugo Sparks'
google_analytics: 
  - 'UA-93008985-3'
  - 'auto'

theme: 
  name: 'material' # 'readthedocs'
  language: 'en'
  search:
    language: 'en, fr' 
## 'Volkorn' 'Libre Baskerville' 'Merriweather'
## https://fonts.google.com
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
## https://fonts.google.com
  palette:
    primary: 'blue-grey'
    accent: 'red'
## red, pink, purple, deep purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey and blue-grey
  logo:
    icon: 'layers'
## https://material.io/icons/
  favicon: 'img/favicon.ico' 
## default, assets/images/favicon.png
  feature:
    tabs: false 
## another layer on top of the main navigation for larger screens in the form of tabs.           
#    social:
#      - type: 'gitlab'
#        link: ''
#        type: 'twitter'
#        link: ''
#      - type: 'linkedin'
#        link: ''
#  disqus: 'your-shortname'
## https://disqus.com/
## repo_icon: 'github' # gitlab, bitbucket

#extra_css: 
#    - 'extra.css'
## in the docs

nav:
  - Home: 'index.md'
  - Vade Mecum:
    - Charts: 'Charts.md'
    - Digital Humanities: 'Digital Humanities.md'
    - Edition Cheat Sheets: 'Edition_CS.md'
    - Infographies: 'Infographies.md'
    - LaTeX Snippets: 'latex_snippets.md'
    - Learn Git: 'Learn Git.md'
    - Resources for Data Science: 'Resources for Data Science.md'
    - Storytelling with Data: 'Storytelling with Data.md'
    - Ten Kinds of Stories to Tell with Data: 'Data_Storytelling.md'
    - Visual Perception (visualisation): 'visual_perception.md'
  - OS & CLI:
    - OS Cheat Sheets: 'OS_CS.md'
    - Codecademy, Learn the Command Line Notes: 'Codecademy Learn the Command Line Notes.md'
    - Command Line Crash Course: 'Command Line Crash Course.md'
    - Command Shell Snippets : 'Command Shell Snippets.md'
    - Install & Run on Linux: 'Install_tarball.md'
    - The Linux Command Line: 'The Linux Command Line.md'
    - Ubuntu 16.04: 'Ubuntu.md'
    - Useful Shell Commands for Data Science: 'Usefull+Shell+Commands+for+Data+Science.md'
  - SQL & NoSQL:
    - SQL-NoSQL Cheat Sheets: 'SQL-NoSQL_CS.md'
    - Codecademy, Learn SQL: 'Codecademy Learn SQL.md'
    - Codecademy, SQL, Analyzing Business Metrics: 'Codecademy SQL, Analyzing Business Metrics.md'
    - Codecademy, SQL, Table Transformation: 'Codecademy SQL, Table Transformation.md'
    - Introduction to SQL JOINs: 'Introduction to SQL JOINs.md'
  - Virtual Machines (Cloud Computing):
    - AWS: 'AWS.md'
    - Cloud Computing: 'Cloud.md'
    - Google Cloud: 'Google_Cloud.md'
  - Web:
    - Web Cheat Sheets: 'Web_CS.md'
    - Embedding HTML into HTML: 'embedding.md'
    - HTML and CSS: 'HTML and CSS.md'
    - Markdown & Pandoc: 'Markdown & Pandoc.md'
    - Responsive HTML: 'Responsive_HTML.md'
    - Tests: 'tests.md'

markdown_extensions:
  - def_list
## to make glossaries
  - fenced_code
## ```python, ~~~~python, ~~~{.python}
  - footnotes
## [^1]: Lorem ipsum
## [^2]:
##     Lorem ipsum 1 (multiline)
##
##     Lorem ipsum 2
  - tables
## |First Header  | Second Header|
## |------------- | -------------|
## |Content Cell  | Content Cell |
## |Content Cell  | Content Cell |
  - admonition 
## https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      linenums: true
## ```python hl_lines="1 2"
## a=1
## ```
## https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - meta
## https://python-markdown.github.io/extensions/meta_data/
## https://squidfunk.github.io/mkdocs-material/extensions/metadata/
  - nl2br
## break the line with a new line or return
  - sane_lists
## numbers vs. bullets
## https://python-markdown.github.io/extensions/sane_lists/
  - smarty
## additional characters: ' "  «  ... -- ---
## watch when copy-pasted
  - toc:
      title: CONTENT
      permalink: true
      anchorlink: false
      baselevel: 3
## permalink link to a subpart of the document
## anchorlink causes all headers to link to themselves.
## https://python-markdown.github.io/extensions/toc/
## https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
##
## Third Party Extensions: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
##
  - pymdownx.arithmatex
## extra_javascript, see below
  - pymdownx.betterem
## bold, italic, both
## https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.caret
## ^^ ^^ underline
  - pymdownx.critic
## markup for commenting, correcting
  - pymdownx.details
## alike admonition, can be nested!
## https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.emoji
## https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
## https://www.emojicopy.com/
## :smile: :heart: :thumbsup:
  - pymdownx.inlinehilite
## https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
## `#!python `
#  - pymdownx.magiclink
## detects links in Markdown and auto-generates the necessary markup
  - pymdownx.mark
## == == highlight
  - pymdownx.smartsymbols
## https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
## +/-  -->  <--  <-->  =/=  1/4  1st 2nd
  - pymdownx.superfences
## nest code blocks under blockquotes
  - pymdownx.tasklist:
      clickable_checkbox: true
## https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
## - [ ]  - [x]
  - pymdownx.tilde
## https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
## ~~ ~~ crossover
  - pymdownx.keys
## https://facelessuser.github.io/pymdown-extensions/extensions/keys/
## ++ctrl+alt+delete++
## MORE
#  - pyembed.markdown
## videos
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
   
